version: "3.9"
services:
    MongoDB:
        image: mongo:latest
        container_name: MongoDB
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - MongoDB:/Database
        ports:  
            - 27017:27017
        restart: unless-stopped

    Mongo-express:
        image: mongo-express:latest
        container_name: Mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=MongoDB
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        ports:
            - 8081:8081
        depends_on:
            - MongoDB
        

volumes:
    MongoDB:
